version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - next-forum:/var/lib/postgresql/data
    container_name: postgres_server
  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4:latest
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    container_name: pgadmin_server
volumes:
  next-forum:
    driver: local
